### PR TITLE
Add Sampling

### PR DESCRIPTION
**Pull request by CSSFrancis**
#### Description of the change

Add in Sampling using reduced symmetry sampling.

Sampling Methods Added:
--------------------------
The first sampling functionality mirrors the S_2 sampling tutorial, but is more explicit such that  given some point group the rotations which rotate some vector [0,0,1] to each sampling vector is returned.  This is used when fast template matching in `pyxem`.

The second sampling method is just a simple method for finding zone axes in simple systems.  I think there are __much better__ ways of doing this and I'd like to improve this method from the old `diffsims` one (and I think kikuchipy already does some of that).

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
from orix.symmetry import C2
from orix.sampling import get_sample_zone_axis
sampling = get_sample_zone_axis(2.0, point_group=C2)
```

#### For reviewers

- [x] The PR title is short, concise, and will make sense 1 year later.
- [x] New functions are imported in corresponding `__init__.py`.
- [x] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [x] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

### CODE REVIEW

**Comment by CSSFrancis** [comment]
@hakonanes Any now I didn't have pre-commit set up correctly.... We should (finally be good)

**Comment by CSSFrancis** [comment]
Hmm I'm not sure why my local pre commit isn't agreeing with orix. 😅 probably some version mismatch or it not running properly for some reason.

@hakonanes any problems with my adding the pre-commit ci to Orix?

That way it will run isort and black on the code either automatically or when you ask it to?

**Comment by hakonanes** [comment]
> Hmm I'm not sure why my local pre commit isn't agreeing with orix

The two code style errors are related to sorting of imports. Do you have `isort` installed? It's among the dev dependencies.

> @hakonanes any problems with my adding the pre-commit ci to Orix?
> That way it will run isort and black on the code either automatically or when you ask it to?

We could add a way to run pre-commit automatically if asked. I'm open to that. However, I think there is a point where there is too much automation in the development process for us to maintain, instead of focusing on functionality. I consider pushes by bots too much. At least for this project at this point in time.

Anyways, I wouldn't worry too much about the code style now. Could you explain a bit more in the top comment what this new functionality does and what its intended use is? Any details about the implementation you can provide would be much appreciated.

**Comment by hakonanes** [comment]
And, please request a review from me when you're ready!

**Comment by hakonanes** [comment]
Also, if you rebase on `develop`, the docs should be passing.

**Comment by CSSFrancis** [comment]
@hakonanes I've updated the head comment with more information.

**Comment by CSSFrancis** [comment]
pre-commit.ci autofix

**Comment by pc494** [comment]
Should be able to review this for you tomorrow @CSSFrancis.

**Comment by CSSFrancis** [comment]
@pc494 Sounds good!  I'll see if I can determine why the test isn't passing.

**Comment by CSSFrancis** [comment]
@pc494 yea I can't tell if that test is flakey or there is some scipy bug related to certain hardware configurations.

**Review by pc494 — APPROVED** [review]
Thanks @CSSFrancis, this looks good to me.

**Review by pc494 — CHANGES_REQUESTED** [review]
Sorry, I spoke to soon, this still needs a Changelog entry the imports as-per the PR template.

**Review by pc494 — APPROVED** [review]
Sorry, had missed that you already had the imports, merging.

**Pull request merged**
