### PR TITLE
Post 0.8.1 release updates

### PR DESCRIPTION
**Pull request by hakonanes**
#### Description of the change
Post 0.8.1 release updates, including a new release guide.

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

### CODE REVIEW

**Comment by hakonanes** [comment]
@pc494 (and @harripj), are you comfortable with the possibility to run the [publish action](https://github.com/pyxem/orix/actions/workflows/python-publish.yml) manually, that is not only by publishing a tagged release? I had to allow for that now (see https://github.com/pyxem/orix/issues/275#issuecomment-1039170431 and below), but can remove it if you think it best to restrict triggering that action to only tagged releases.

**Comment by harripj** [comment]
Good idea to make a release guide!

**Comment by hakonanes** [comment]
Feel free to merge this whenever it's convenient.

**Comment by harripj** [comment]
Merging now.

**Pull request merged**
