### PR TITLE
Modify spacegroup2pointgroup conversion to include improper point groups

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

* Changed location and name of function `orix.sampling.sampling_utils._get_proper_point_group()` to `orix.quaternion.symmetry._get_point_group()`
* Added a `proper: bool = False` parameter to `_get_point_group()`, returning either the proper or "improper" point group from the old `conversion_dict`. Since the name is now `_get_point_group()`, default is to return the improper point group.
* Added "improper" point groups to the `conversion_dict` space group to point group conversion dictionary. Also moved the dictionary to `orix.quaternion.symmetry`.
* Moved and updated tests accordingly

This PR, or a version of it, is necessary when deriving the point group from the space group in the `Phase` class. The idea is that when you define a `Phase` specifying a space group, you don't necessarily want the proper point group, just the point group.

Feel free to change the setup of the dictionary (proper/improper) or propose a change if you think it's ugly and can be done better.

I'm sure the docstring wording can be improved also.

Example usage:
```python
>>> from orix.quaternion.symmetry import _get_point_group
>>> from diffpy.structure.spacegroups import GetSpaceGroup
>>> sg225 = GetSpaceGroup(225)
>>> sg225.short_name
'Fm-3m'
>>> sg225.point_group_name
'PGm3barm'
>>> _get_point_group(225).name
'm-3m'
>>> _get_point_group(225, proper=False).name
'm-3m'
>>> _get_point_group(225, proper=True).name
'432'
```

### CODE REVIEW

**Comment by hakonanes** [comment]
I should note that the update to the space group to point group conversion dictionary is based upon Table 10.2 in De Graef and McHenry's Structure of Materials.

**Comment by pc494** [comment]
If this is ready for a review I'll get on it later today?

**Comment by hakonanes** [comment]
Yes, it's ready for review.

I try to always remember to use the WIP label if the PR is not ready for review.

**Comment by pc494** [comment]
> Yes, it's ready for review.
> 
> I try to always remember to use the WIP label if the PR is not ready for review... A better way would be for me to request a review!

Sorry, in the past we've worked the other way around (requesting reviews rather than using the WIP label) because when there are only 2 devs you know whose going to be reviewing! For `orix` will developers using your method seems the best option

**Comment by hakonanes** [comment]
> Sorry, in the past we've worked the other way around (requesting reviews rather than using the WIP label) because when there are only 2 devs you know whose going to be reviewing! For `orix` developers using your method seems the best option

You might be right. We could add a `ready-for-review` label...

**Pull request merged**
