### PR TITLE
Improve plotting of vector labels

### PR DESCRIPTION
**Pull request by hakonanes**
#### Description of the change
This PR improves plotting of vector labels in the stereographic projection by:
* Adding convenience function `orix.plot.format_labels(v, brackets=("", ""), use_latex=True)` accepting an array of vectors and returning an array of strings, one integer label per vector.
* Adding an `offset=None` parameter in `StereographicPlot.text()` to control offset in stereographic coordinates (X, Y). When plotting with `Vector3d.scatter(..., vector_labels=labels)`, this offset can be passed via `text_kwargs={"offset": (0, 0.02)}"`.

This makes labeling a pole figure much easier and nicer.

We can consider "extending" the `vector_labels` in `Miller.scatter()` by allowing it to be `True`, which then automatically creates the labels and adds them accordingly with the correct brackets (hkl/uvw). The danger is that this labeling assumes integer coordinates which might not be true for all vectors. If we add this, a warning should be raised in the case where rounding introduces an error in the coordinate labels above a certain threshold.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)
- [x] Account for Miller-Bravais (hkil) and Weber [UVTW]

#### Minimal example of the bug fix or new feature
Create three sets of direct lattice vectors \<uvw\> and plot them in the stereographic projection with labels and one color per family of directions

```python
from orix import plot
from orix.crystal_map import Phase
from orix.vector import Miller


h = Miller(uvw=[[0, 0, 1], [1, 1, 1], [1, 1, 0]], phase=Phase(point_group="m-3m"))
h2, idx = h.symmetrise(unique=True, return_index=True)

h2.scatter(
    c=np.array([f"C{i}" for i in range(h.size)])[idx],
    vector_labels=plot.format_labels(h2.uvw, ("[", "]")),
    text_kwargs=dict(offset=(0, 0.02), bbox=dict(fc="w", ec="none", pad=0, alpha=0.75))
)
```

test

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

### CODE REVIEW

**Comment by pc494** [comment]
Sorry @hakonanes, I should have reviewed this. Can I get it sometime next week once the conflicts (also my fault) have been resolved?

**Comment by hakonanes** [comment]
No problem, sounds good! Will fix the conflicts.

**Comment by hakonanes** [comment]
By 'no problem', I mean thanks for reviewing :)

**Comment by hakonanes** [comment]
Conflicts fixed, should be ready for review!

**Review by harripj — APPROVED** [review]
Sorry for the delay @hakonanes, this change looks great and will be helpful to users wanting to improve their figures. Would you mind if I make a very minor change to one of the notebooks just to add `offset` to one of the plots?

**Review by pc494 — APPROVED** [review]
This looks good to me, I'll check @harripj got his change in and then mege.

**Comment by harripj** [comment]
@pc494 feel free to merge!

**Comment by hakonanes** [comment]
Great, thank you guys for having a look! Will merge once the Python 3.7 build succeeds.

**Pull request merged**
