### PR TITLE
Remove restriction to upload to PyPI via action

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

#### Description of the change
See https://github.com/pyxem/orix/issues/299#issuecomment-1122451887.

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [n/a] Unit tests with pytest for all lines
- [n/a] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

### CODE REVIEW

**Comment by hakonanes** [comment]
Good questions.

The "publish" action is only triggered if we
1. publish a tagged release or
2. trigger it manually

Currently, an upload to PyPI is attempted in case 1. If this PR is merged, an upload is also attempted in case 2.

An upload to PyPI is successful if the attempted upload's version isn't available on PyPI. This means that we cannot upload two 0.9.0, for example. If 0.9.0rc1 isn't on PyPI, it will be uploaded. See for example [NumPy's](https://pypi.org/project/numpy/#history) PyPI release history.

**Comment by harripj** [comment]
Thanks for answering! I see, the RC release is not tagged, so the upload needs to be triggered manually, but the action currently prevents the release due to the `if` statement. Yes we should correct this behaviour.

**Review by harripj — APPROVED** [review]

**Comment by hakonanes** [comment]
Actually, the RC release *was* tagged as `v0.9.0rc1`, but the tagged version of `master` couldn't be uploaded due to the unsupported "raw" directive included in the reST string passed to `long_description` in `setup()`. We fixed this, but there is no way to update the tag via GitHub. The alternative is to
1. Delete the release on GitHub (upstream)
2. Overwrite the upstream tag locally, including the updates
3. Force push the new local tag to upstream
4. Create new release on GitHub pointing to the new tag

**Comment by hakonanes** [comment]
It's worth mentioning that we can delete uploads to PyPI via their web page if we uploaded something accidentally.

**Comment by harripj** [comment]
Merging.

**Pull request merged**
