### PR TITLE
Bump version to v0.8.dev0 and add Paddy Harrison (@harripj) to credits

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

#### Description of the change
* Bump version to v0.8.dev0 after v0.7.0 was released :tada:
* Change `__author__` to "orix developers"
* Add Paddy Harrison (@harripj) to `__credits__`. If you don't want this, or be entered with another name, @harripj, please say so!
* Sort contributors in `__credits__` by line contributions after initial committer @bm424. Should we instead sort this by number of commits or alphabetically? We sort by line contributions in [kikuchipy](https://github.com/pyxem/kikuchipy/blob/develop/kikuchipy/release.py#L24).
* Remove unnecessary `style.css` file in docs.

#### Progress of the PR
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix import vector
>>> v = vector.Vector3d([1, 1, 1])
>>> # Your new feature...
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

### CODE REVIEW

**Review by pc494 — APPROVED** [review]
Happy with this. I think the credits ordering makes sense. Merging.

**Comment by hakonanes** [comment]
@harripj, we'll remove you from the `__credits__` list if you don't want to be there.

**Comment by harripj** [comment]
@hakonanes happy to be there and to contribute!

**Comment by hakonanes** [comment]
@harripj, great! I'm sorry you weren't added sooner; from now on we'll add all contributors to the `__credits__` list.

**Pull request merged**
