### PR TITLE
Check user guide notebooks stored with cell outputs regularly

### PR DESCRIPTION
**Pull request by hakonanes**
#### Description of the change
Add a GitHub Action checking that the cell outputs in user guide notebooks stored with cell outputs (clustering_orientations.ipynb, clustering_misorientations.ipynb) can be reproduced with the current code in `master`. This is necessary because the code that produced the cell outputs the notebooks were stored with is gradually getting older, unless we re-run the notebooks and push the changes to `master` with every change in orix. The action runs weekly on Mondays and is identical to [this one](https://github.com/pyxem/kikuchipy/blob/develop/.github/workflows/test_documentation_notebooks.yml) in kikuchipy.

The two mentioned notebooks have cell output stored because they are computationally demanding, and Read the Docs' machine only provides 3 GB of RAM.

Since the action is identical to one working fine for kikuchipy, I haven't run it specifically for orix. I'll ensure that the action runs the following Monday after this PR is merged.

These changes address the tasks in #297.

I've also adjusted the presentation of the logo in the README slightly so that it is of a constant size (works better on mobile), removed the reference to the demos, and added links to both the journal and arXiv version of the clustering paper. Finally, I added the recent pyxem orientation mapping paper to "Work using orix", above the orientation clustering paper.

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [n/a] Unit tests with pytest for all lines
- [n/a] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)
- [x] Merge #318
- [x] Merge #317

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

### CODE REVIEW

**Comment by harripj** [comment]
Happy with this, just have to check the Action runs as expected on Monday. Thanks!

**Review by harripj — APPROVED** [review]

**Comment by hakonanes** [comment]
Just realized that the notebooks cannot be run since the "Ti_orientations.ctf" files are not available upon runtime. This PR will have to wait a bit, I think.

**Comment by hakonanes** [comment]
Or, it can be downloaded as is done in the [CrystalMap notebook](https://orix.readthedocs.io/en/stable/crystal_map.html#Load-or-create)... I think it is about time to add the `orix.data` module which these data sets can be conveniently downloaded from (see #149).

**Comment by harripj** [comment]
Given that we only need 3 columns from the dataset we could make a smaller file (attached here, size ~4MB), which we could include in a `data` directory, for example. What do you think?

```python
>>> euler = np.loadtxt('Ti_orientations.ctf', skiprows=1, usecols=(0, 1, 2))
>>> euler2 = np.loadtxt('Ti_orientations.txt')
>>> np.allclose(euler, euler2, atol=1e-4)
True
```
[Ti_orientations.txt](https://github.com/pyxem/orix/files/8425938/Ti_orientations.txt)

**Comment by harripj** [comment]
> I think it is about time to add the orix.data module which these data sets can be conveniently downloaded from (see https://github.com/pyxem/orix/issues/149).

Beat me to it! Happy with this and the implementation as discussed in #149. Of note, in the notebooks we should mention the file size before people run and download the code, just to be explicit, as one of the files is ~3GB.

**Comment by hakonanes** [comment]
I plan to implement the `orix.data` directory as the [`kikuchipy.data`](https://github.com/pyxem/kikuchipy-data) directory, using on [`pooch`](https://www.fatiando.org/pooch/latest/) (light dependency), which allows datasets to be downloaded from an external repository to your local cache. How it works in kikuchipy is described [here](https://kikuchipy.org/en/stable/contributing.html#adding-data-to-the-data-module).

> one of the files is ~3GB

Which file is this? What I'm suggesting is to upload the "Ti_orientations.ctf" file (~26 MB) to its orix-data repo (similar to the [kikuchipy-data]() repo), point to this in the `orix.data` module, and allow download via `ctf = orix.data.ti_orientations(allow_download=True)`, just like `s = kp.data.nickel_ebsd_large(allow_download=True)` ([see user guide](https://kikuchipy.org/en/stable/user_guide/pattern_matching.html#Pattern-matching)). We can then compute the disorientation matrices on the fly.

**Comment by harripj** [comment]
Okay, sounds good, should we make all of the [data](https://drive.google.com/drive/folders/1jJBWlOD3Q7klpEU3PvtSrp7Lmcn5o1af) for the notebooks accessible in this fashion? 

The `ori-distance((100, 200)).npy` array is 3GB. But if I gather, you are suggesting to have the user compute this locally? Happy with this too as long as it doesn't take too long. Could also be computed locally for the `Mismisorientation` distance if the [new implementation](https://github.com/pyxem/orix/issues/315#issuecomment-1090033022) is also reasonably quick!

**Comment by hakonanes** [comment]
> should we make all of the [data](https://drive.google.com/drive/folders/1jJBWlOD3Q7klpEU3PvtSrp7Lmcn5o1af) for the notebooks accessible in this fashion?

The raw data, Ti_orientations.ctf and the SDSS .ang and orix HDF5 files, should be added I think.

> The ori-distance((100, 200)).npy array is 3GB.

Of course, sorry for forgetting that! I suggest to leave that in Google Drive. The file is also too large for Read the Docs to handle, so I think the cell outputs in the notebook orientation clustering should have to be left as is.

> But if I gather, you are suggesting to have the user compute this locally? Happy with this too as long as it doesn't take too long.

It takes about 1min 11s on my 5 year old machine with 4 CPUs.

> Could also be computed locally for the Mismisorientation distance if the https://github.com/pyxem/orix/issues/315#issuecomment-1090033022 is also reasonably quick!

This turns out to be unnecessary: as long as "Ti_orientations.ctf" is available for download within the misorientation clustering notebook, the notebook can be run as is by Read the Docs. We can store this notebook without cell outputs and run it as the other notebooks without issue.

**Comment by hakonanes** [comment]
I'll update this PR and make it ready for review once #318 is merged and the "Ti_orientations.ctf" file is available via `orix.data.ti_orientations()`.

**Comment by hakonanes** [comment]
Let's wait for #317 to be merged before revisiting this.

**Comment by hakonanes** [comment]
Note that I rebased on the latest commits on `master`.

**Comment by hakonanes** [comment]
I should have taken more care with which notebooks were updated, since I see that e.g. the point group visualization just got some spaces reduced...

**Comment by harripj** [comment]
This PR now has conflicts with master.

**Comment by hakonanes** [comment]
Fixing...

**Comment by harripj** [comment]
Sorry, did not mean that, will rebase.

**Comment by hakonanes** [comment]
It's not a problem, I think, I can work with that merge.

**Comment by harripj** [comment]
Yes I think it was just a merge from your branch. Sorry about that in any case.

**Comment by hakonanes** [comment]
Congratulations on the Ultramicroscopy paper, @harripj! You use and cite orix in the paper. Do you want to list it in "Work using orix" in the docs?

**Comment by harripj** [comment]
Thanks @hakonanes! Yes I was planning to suggest this in the near future- the paper was only recently accepted and the version online is still a pre-proof. Once we get a bit further down the publishing road I will suggest this. More related work to come too!

**Comment by hakonanes** [comment]
> Once we get a bit further down the publishing road I will suggest this

The only thing I see that's missing is the journal volume number. That is missing for the pyxem orientation mapping paper as well, but we will add it to the list anyway. If you're OK with it, I'd like to add it to the list in this PR.

I cannot find a version on arXiv, so I assume it's not available there? Then we'll just link to the journal version.

> More related work to come too!

Exciting!

**Comment by hakonanes** [comment]
This PR is done from my part :)

**Comment by harripj** [comment]
> The only thing I see that's missing is the journal volume number. That is missing for the pyxem orientation mapping paper as well, but we will add it to the list anyway. If you're OK with it, I'd like to add your paper to the list in this PR. Nevermind, will of course respect your decision. We'll wait!

Happy to add it here in fact! I see that the the pyxem orientation mapping paper is also being added in this PR, so would make it easier to bundle them together.

> I cannot find a version on arXiv, so I assume it's not available there? Then we'll just link to the journal version.

No it's not available on arXiv, just a link to the journal will be fine!

**Comment by hakonanes** [comment]
> Happy to add it here in fact!

OK, I've added it to the top of the list (descending chronological order).

**Comment by harripj** [comment]
> OK, I've added it to the top of the list (descending chronological order).

Thanks @hakonanes!

**Comment by pc494** [comment]
> Thanks @hakonanes! Yes I was planning to suggest this in the near future- the paper was only recently accepted and the version online is still a pre-proof. Once we get a bit further down the publishing road I will suggest this. More related work to come too!

It's a nice paper, does need some proofing though! If the DOI in the link is where it's final home will be I'll get on and review this this evening :)

**Comment by hakonanes** [comment]
> If the DOI in the link is where it's final home will be

That should be the case.

**Pull request merged**
