### PR TITLE
Segmenting of the stereographic projection

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

#### Description of the change
This PR aims to allow drawing segment boarders in the stereographic projection, which will mostly be used for triangles.

I set up this PR so that others can contribute with comments on the API etc. It is still highly a work in progress.

See discussion in #169 and #166. 

#### Progress of the PR
- [ ] Figure out what to call `Symmetry.fundamental_sector()`, since I'd like to call the new property `Symmetry.fundamental_sector`, as per discussions in #169.
- [x] Ensure the sector looks correct for all 32 point groups.
~- [ ] Add `Vector3d.plot()` to draw lines between points (like the triangle). This is different from `scatter()` and `draw_circle()`.~ Will be added in a later PR. Only added to `StereographicPlot.plot()` here.
- [ ] Allow plotting only a segment of the stereographic projection, defined e.g. by a fundamental sector, which typically is the inverse pole figure.
- [x] Add S2 UV sampling in new `orix.sampling.S2_sampling.uniform_S2_sample()` function. Necessary to get center vector for some point groups' fundamental sectors.
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
Plotting the fundamental sector of point group m-3m in the stereographic projection

```python
>>> import matplotlib.pyplot as plt
>>> from orix.quaternion.symmetry import T
>>> fs = T.fundamental_sector
>>> fig, ax = plt.subplots(subplot_kw=(projection="stereographic"))
>>> ax.scatter(fs.vertices, c="r")
>>> ax.plot(fs.edges, color="g")
>>> ax.scatter(fs.center, c="b")
```

produces this plot in stereographic projection (equal angle)

orix_28_T_23_laue_23_pf

From MTEX in equal area projection

28_T_laue_m-3_pf

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

### CODE REVIEW

**Comment by hakonanes** [comment]
This PR is getting there, although there's lots of work left. I'm pretty sure I'll close this PR and make a new one from a new branch, since there is lots of trial and error here.

The framework in this PR only focuses on internal use, and little new public API will be added.

We're able to restrict the stereographic axes (xaxis - azimuth, yaxis - polar) using a `SphericalRegion`, most likely a `FundamentalSector` derived from a `Symmetry`:

```python
>>> import matplotlib.pyplot as plt
>>> from orix import plot, quaternion
>>> pg = quaternion.symmetry.Td
>>> fig, ax = plt.subplots(subplot_kw=dict(projections="stereographic"))
>>> ax.grid()
>>> pg.fundamental_sector.vertices
Vector3d (3,)
[[ 0.5774  0.5774  0.5774]
 [ 0.      0.      1.    ]
 [ 0.5774 -0.5774  0.5774]]
>>> ax._restrict_to_fundamental_sector(pg.fundamental_sector)
```

Td_restricted

**Comment by pc494** [comment]
Just for documentation purposes, I'm fairly sure that the sampling you've brought over from diffsims is of S2, not SO(2)

**Comment by hakonanes** [comment]
> Just for documentation purposes, I'm fairly sure that the sampling you've brought over from diffsims is of S2, not SO(2)

Yup, will change. Thanks.

**Comment by hakonanes** [comment]
To not use up CI resources, I'll close this, but open a new PR once ready.

**Pull request closed without merging**
