### PR TITLE
Replace numpy-quaternion with quaternionic.

### PR DESCRIPTION
**Pull request by CSSFrancis**
#### Description of the change
As per #506.

I'm running into some problems making this change becuase I'm not really sure what the  improper `setter` functions works with the `_data` attribute.

The difference arrises from quaternionic forcing having 4 as the last shape and not automatically casting as the numpy-quaternion package does.

```python

import quaternionic as quaternion2
import quaternion
import numpy as np

quaternion.as_float_array(np.ones((10,4))).shape 
# (10, 4, 4)

quaternion2.array(np.ones((10,4))).shape
# (10,4)
```

@hakonanes any advice for what might need to change as a result?

#### Progress of the PR
- [ ] [Docstrings for all functions](https://numpydoc.readthedocs.io/en/latest/example.html)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/dev/code_style.html)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

### CODE REVIEW

**Comment by CSSFrancis** [comment]
Okay so we might have to adjust how we do things. 

1. I think that the data for a Quaternion should always be a `quaternion` class from quaternionic. 
2. The rotation class should be Quaternion + a boolean for proper/ improper.  I think the right thing to do would be to make a numpy array class for this but.... Maybe we should just sperate these two arrays into data + improper.

**Comment by pc494** [comment]
It looks like we might get a downstream fix now, which would be excellent.

https://github.com/moble/quaternion/issues/229

**Comment by hakonanes** [comment]
Sorry for answering late here...

The dependency on numpy-quaternion is NOT important. We only use it for quaternion-quaternion and quaternion-vector multiplication. Our "old" implementation used Numba, and as far as I can remember, it was only twice as slow.

If numpy-quaternion becomes a hassle, I'd suggest we make it an optional dependency: use it when available, but fall back to Numba if it's not. What do you think?

**Comment by hakonanes** [comment]
And I should say, I find storing the rotation handedness (proper -> right-handed, improper -> left-handed; or, if you will, the rotation followed by an inversion) as a fifth value 0 or 1 in the `Rotation._data` array is rather elegant and makes the implementation easier.

**Comment by pc494** [comment]
I think this is safe to close.

@CSSFrancis any objection?

**Pull request closed without merging**
