### PR TITLE
Prepare 0.9.0rc1 release candidate

### PR DESCRIPTION
**Pull request by hakonanes**
#### Description of the change
This PR is made in preparation of the release candidate 0.9.0rc1 discussed in https://github.com/pyxem/orix/issues/299. The release can be made after it is merged.

@harripj is moved above @dnjohnstone in the credits list since he has more line additions.

Minor improvements to the documentation is made. All notebooks run as expected on my machine.

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [n/a] Unit tests with pytest for all lines
- [n/a] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

### CODE REVIEW

**Comment by hakonanes** [comment]
> deal with Zenodo for 0.9

I can add the Zenodo JSON file in this PR if you want. I'm OK with us maintaining this file.

> commits or line additions?

My vote is for line additions without notebooks, but I haven't found a way to list line additions per author (or email) excluding notebook files. I think the `git-fame` tool might be what we're after, but I couldn't get it to calculate exactly the above (see [this issue](https://github.com/casperdcl/git-fame/issues/72)). So, for now, I my vote is for line additions.

> where should we put Ben (my vote would be to assign him to 1 more commit/line addition than me)

As mentioned previously, my vote is for keeping the original commiter(s) first. But you are the senior here, @pc494, so I defer to you.

**Comment by pc494** [comment]
> I can add the Zenodo JSON file in this PR if you want. I'm OK with us maintaining this file.

That would be excellent thank you.
 
> My vote is for line additions without notebooks, but I haven't found a way to list line additions per author (or email) excluding notebook files. I think the `git-fame` tool might be what we're after, but I couldn't get it to calculate exactly the above (see [this issue](https://github.com/casperdcl/git-fame/issues/72)). So, for now, I my vote is for line additions.

Line additions, with line additions excluding notebooks if that becomes available sounds good to me.

> As mentioned previously, my vote is for keeping the original commiter(s) first. But you are the senior here, @pc494, so I defer to you.

I've had another look at the code base at the point Ben left academia, and I'm still of the opinion that the additions and adjustments you have made are sufficiently significant to have you as the the lead on the DOI of this code. I think this is more consistent with open source ideas broadly than offering "ownership by priority" would be. Furthermore, Ben is on the "introducing orix" manuscript, which I think ties his contribution off nicely.

**Comment by hakonanes** [comment]
Suggested release notes:

# orix 0.9.0rc1

orix 0.9.0 is a minor release of orix, an open-source Python library for handling orientations, rotations and crystal symmetry.

This version contains many small and some larger changes, including enhancements to existing classes and bug fixes. See [the changelog](https://github.com/pyxem/orix/blob/master/CHANGELOG.rst) or https://github.com/pyxem/orix/compare/v0.8.2...v0.9.0rc1 for a complete list of changes.

Notable changes:
* `orix.scalar.Scalar` has been removed, so the data held by `Scalar`, like class properties `Rotation.angle`, `Vector3d.azimuth` and so on, are returned directly as a `numpy.ndarray`.
* Creating rotations from Euler angles interprets the angles in the Bunge convention by default, i.e. rotations are transformations from the sample to the crystal.
* Reducing memory usage when computing the misorientation distance matrix, rotation outer products and quaternion-vector outer products have been added via lazy computation with `dask`.
* The alignment of crystal axes in the package is documented in the user guide.

**Comment by hakonanes** [comment]
> My only thought is to change the first line of the note to "orix 0.9.0 will be" to help avoid confusion.

I was wondering how to best do this, so I looked at how NumPy [describes their pre-releases](https://github.com/numpy/numpy/releases/tag/v1.22.0rc3): They don't mention that it is a pre-release in any of their 1.22.rc1-3 release candidates. The only hint people have is the "rc" and that the release is tagged as pre-release. If you think this is insufficient still, I can update the wording.

**Comment by harripj** [comment]
> I was wondering how to best do this, so I looked at how NumPy describes their pre-releases: They don't mention that it is a pre-release in any of their 1.22.rc1-3 release candidates. The only hint people have is the "rc" and that the release is tagged as pre-release. If you think this is insufficient still, I can update the wording.

I think this is okay. My feeling is writing like this is the 0.9 release saves corrections later, and hopefully people will understand this release is a release candidate from the 'rc' in the version number.

**Comment by pc494** [comment]
Yeah I was going to say, unless you checked with somebody else sensible, which numpy certainly is. In which case is this PR now good for me to give a once over and merge?

**Pull request merged**
