### PR TITLE
Packaging commits (Changelog and release)

### PR DESCRIPTION
**Pull request by pc494**
#### Description of the change
We used to do this as manual single commits but this is slightly nicer. Will still self merge though.

### CODE REVIEW

**Review by hakonanes — APPROVED** [review]

**Comment by hakonanes** [comment]
To half the number of PR checks, I recommend making PRs from branches in forks...

**Comment by pc494** [comment]
> To half the number of PR checks, I recommend making PRs from branches in forks...

Honestly, I had forgotten it was two commits and not one.

**Comment by pc494** [comment]
will stop doing it like that then

**Comment by hakonanes** [comment]
We could remove the `push` part, but then checks wouldn't be run on `master` after a PR is merged:

https://github.com/pyxem/orix/blob/9889817132eed74d7229ca7f6c05ab88cdffd16c/.github/workflows/build.yml#L1-L3

> will stop doing it like that then

To save GitHub some energy for computing power, and by extension the Earth!

**Pull request merged**
