### PR TITLE
Add CrystalMap.plot(), use matplotlib-scalebar, add xmap notebook

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

#### Description of the change
This PR aims to make plotting a CrystalMap simpler.

* Add CrystalMap.plot() method (using `orix.projections.CrystalMapPlot`, similar to `Vector3d.plot()` and `Miller.plot()`)
* Move CrystalMap notebook from orix-demos and improve it
* Use [matplotlib-scalebar](https://github.com/ppinard/matplotlib-scalebar/) instead of directily using Matplotlib's AnchoredSizeBar. This enables us to remove lots of code, and brings easier customization of the scalebar.
* Add attributes `scalebar` and `colorbar` to `CrystalMapPlot` for easy access, which are `None` until `add_scalebar()` and `add_colorbar()`, respectively, are called.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)
- [x] Finish notebook editing
- [x] Finish testing of CrystalMap.plot()

#### Minimal example of the bug fix or new feature
This code

```python
>>> xmap
Phase   Orientations                 Name  Space group  Point group  Proper point group       Color
    1   6043 (51.6%)      ferrite/ferrite         None          432                 432    tab:blue
    2   5657 (48.4%)  austenite/austenite         None          432                 432  tab:orange
Properties: iq, dp
Scan unit: um
>>> fig = xmap.plot(overlay="dp", remove_padding=True, return_figure=True)
>>> fig.savefig("/home/hakon/phase_map_dp.png", bbox_inches="tight", pad_inches=0)
```

produces this phase plot with dot product values in overlay

phase_map_dp_map

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

### CODE REVIEW

**Comment by hakonanes** [comment]
Note that most of the added lines are from the notebook.

**Comment by hakonanes** [comment]
This is ready for review (the notebook can be reviewed here: https://orix--185.org.readthedocs.build/en/185/crystal_map.html). There is no rush, but I would like for it to be part of v0.6.

**Comment by pc494** [comment]
This looks good at a glance, I'll add it to the chunk of stuff I do when I get back to #175, will easily make it into v0.6

**Comment by hakonanes** [comment]
The notebook has changed very little from the one in orix-demos ([nbviewer link](https://nbviewer.ipython.org/github/pyxem/orix-demos/blob/master/04%20-%20Manipulating%20data%20in%20a%20crystallographic%20map.ipynb)), apart from way simpler plotting. The most valuable feedback for me (although all feedback is appreciated!) would be on the `CrystalMap.plot()` method API, i.e. is it sufficiently customizable and behaves as expected.

**Review by pc494 — APPROVED** [review]
I'm looking forward to putting this code through it's paces

**Comment by hakonanes** [comment]
Awesome, thanks a lot! Looking forward to using it myself, as it makes life much easier...

**Pull request merged**
