### PR TITLE
Restructure docs into Tutorials, Examples and improved API reference

### PR DESCRIPTION
**Pull request by hakonanes**
#### Description of the change
See #372. To review changes, see https://orix--378.org.readthedocs.build/en/378/.

* Restructure API reference into one thing per page
* Make API reference comply with most of the numpydoc standard (some things are ignored in the `conf.py`). This required many small and larger changes in the docstrings.
* Move user guide to tutorials, accessed via new URL https://orix.readthedocs.io/en/latest/tutorials/...
* Remove `Object3d.get_plot_data()` and update `RotationPlot.transform()` which was the only place where it was used.
* Remove `Object3d.check()`, `Quaternion.check_quaternion()` and `Vector3d.check_vector()`, as these were not used internally.
* Add examples, one e.g. detailing use of orix plot types in combination with Matplotlib to create a figure with four subplots (addressing #332).
* Add link to GitHub discussions on main doc page, which I think we should start using.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)
- [x] Complete touch-ups of tutorials (old user guides)
- [x] Move some parts of tutorials to examples (Wullf net, symmetry elements in stereographic projection, things like this more suitable as examples to make the tutorials more focused)
- [x] Fix API reference (update docstrings, module docstrings etc.)
- [x] Fix docstring examples so they all work as written (tested using doctest)
- [x] Update contributing guide

#### For reviewers

- [x] The PR title is short, concise, and will make sense 1 year later.
- [x] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

### CODE REVIEW

**Comment by hakonanes** [comment]
There is a lot here to review. I suggest to review by inspecting the new documentation built from this PR, https://orix--378.org.readthedocs.build/en/378/, and commenting based on that.

**Review by pc494 — APPROVED** [review]
This looks good to me, two thoughts:

1) On the front page I think the 'reference' section should be 'API reference'
2) On Contributing, is it worth linking the Discussion section? Also, pointing out that our contribution workflow is very normal for Python and so the time you spend reading it will not be wasted.

These comments are at your discretion @hakonanes and this is an approval.

**Comment by hakonanes** [comment]
Thanks for the quick and helpful review, Phillip!

>  On the front page I think the 'reference' section should be 'API reference'

I agree, and have made that change. All mentions (via the reST :doc:\`reference/index\`) of this should now read "API reference".

> On Contributing, is it worth linking the Discussion section?

This is now done both in the contributing guide under "Questions, comments, and feedback" and on the landing page under "Contributing".

> Also, pointing out that our contribution workflow is very normal for Python and so the time you spend reading it will not be wasted.

Agree, I've added this to the "Tip" note at the top of the contributing guide:

*That said, our contributing workflow is typical for Python projects, so reading this guide can make contributing to similar projects in the future much smoother!*

**Comment by hakonanes** [comment]
FYI, I opened the GitHub Discussions section: https://github.com/pyxem/orix/discussions/379.

**Comment by hakonanes** [comment]
Unless you have any further comments @pc494 or @harripj, I plan to merge this, solve #335, and release v0.10.0, most likely early next week.

**Comment by harripj** [comment]
@hakonanes sorry for the delay! The changes look great to me!

I just have one comment (but it may be outdated), in the PR progress one of the progress points is: _Move some parts of tutorials to examples (Wullf net, symmetry elements in stereographic projection, things like this more suitable as examples to make the tutorials more focused)_. When I check the new _Examples_ section in the Read The Docs I only see the “Subplots” notebook. Just FYI if this is not what you expected!

**Comment by hakonanes** [comment]
Thank you for having a look, @harripj. When I have time Monday afternoon, I'll make the mentioned changes including a brief example showing how to plot IPDFs.

Also, I planned to update the README to something like the [kikuchipy README](https://github.com/pyxem/kikuchipy#readme), without the contributors section. I'll request new reviews after pushing those changes.

**Review by harripj — APPROVED** [review]

**Comment by hakonanes** [comment]
Since you've both already approved the PR (thanks), I'll merge tomorrow Saturday, and then solve #335 and make a release PR.

**Comment by harripj** [comment]
Thanks @hakonanes I really like the new docs style 📕🚀

**Comment by hakonanes** [comment]
Tests are failing due to a Matplotlib warning now becoming an error in just released v3.6. Tracked here in #381. Should be OK to merge this and fix the issue in another PR.

**Pull request merged**
