### PR TITLE
Merge develop into main for release v0.10.0

### PR DESCRIPTION
**Pull request by hakonanes**
#### Description of the change

This PR brings `develop` into `main` with updates of the changelog and version.

A release draft will be made when this PR is merged, which I'll publish after confirming its contents.

I made two changes not in `develop` (these will be brought into `develop` in a PR immediately after release):
1. Change axes (a, b) in `Symmetry.plot()` to the correct (e1, e2), which are two of the three orthonormal Cartesian reference frame axes the crystal axes (a, b, c) defined with respect to. The tutorial covering plotting of symmetry operations now point to the tutorial covering this crystal axes alignment for explanations of (e1, e2).
2. Reduce the spread of the orientation clusters in the tutorial covering clustering across fundamental region boundaries: the orientations are generated with some randomness, and in some cases DBSCAN clusters what was supposed to be three clusters into two instead, which was not in line with the message of the tutorial. I re-ran the tutorial a couple of times after changing the orientation spread to ensure that it produces expected results every time, which it does.

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix.quaternion import symmetry
>>> symmetry.Oh.plot()
```

oh

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

### CODE REVIEW

**Comment by hakonanes** [comment]
The new commits not in `develop` are from [bd0d5c8](https://github.com/pyxem/orix/pull/385/commits/bd0d5c86005fee332f1cadb039e99506678d31f2) and newer.

**Review by pc494 — APPROVED** [review]
I've checked the two listed additions and they look good. Approved.

**Comment by pc494** [comment]
Think @harripj might have overtaken me for contributing now though

**Comment by hakonanes** [comment]
Thank you, Phillip. I'll update the credits ordering.

**Pull request merged**
