### PR TITLE
Bump oldest supported Python version to 3.7

### PR DESCRIPTION
**Pull request by harripj**
#### Description of the change
As discussed in #343 Python 3.6 is deprecated, but currently used in CI as the oldest supported version. This is preventing implementation of type hinting (as discussed in #338) into the code base as `annotations` from `__future__` is only available in Python 3.7+.

In this PR the oldest Python version used in CI is bumped to 3.7. A guide for implementing type hints is introduced into the contributing guide.

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [n/a] Unit tests with pytest for all lines
- [n/a] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [x] The PR title is short, concise, and will make sense 1 year later.
- [n/a] New functions are imported in corresponding `__init__.py`.
- [x] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [x] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

### CODE REVIEW

**Review by hakonanes — CHANGES_REQUESTED** [review]
This looks very good to me, just a minor point about the changelog.

I suggest to wait to merge this till tomorrow after the new branches `develop` (current `master`) and `main` are created. (See #243.)

**Comment by hakonanes** [comment]
Note that I've renamed the "master" branch to "develop". I hope this doesn't cause any surprises for you @harripj.

**Comment by hakonanes** [comment]
[This documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) might be useful.

**Comment by harripj** [comment]
This is now pointing at the `develop` branch.

**Review by hakonanes — APPROVED** [review]

**Comment by hakonanes** [comment]
I'll merge after getting a cup of coffee :coffee:

**Pull request merged**
