### PR TITLE
Update documentation to use Jupyter notebooks, add contributing guide

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

Implement most changes suggested in #149:
* Build user guide pages in the [Read The Docs documentation](https://orix.rtfd.io) from Jupyter Notebooks with [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.1/). A simple notebook showing the new stereographic projection is added as an example, will expand this notebook and add more in later PRs. The user guide notebooks can be run with Binder in the browser!
* nbsphinx and ipykernel are added as new `doc` dependencies
* A Sphinx gallery with the stereographic projection notebook is placed on the front page of the RtD documentation. How to work with this gallery is included in the contributing guide.
* Add a contributing guide based upon the one we have in [kikuchipy](https://kikuchipy.org/en/stable/contributing.html)
* Move `CHANGELOG.md` from the top directory to `doc/CHANGELOG.rst`, to be included in the new documentation section "Help & Reference", which also includes the API reference, the contributing guide and a "Related projects" page
* Moved the installation guide to it's own page in a "Getting started" section. Don't know what else should go here.

This PR is more or less complete, but will have another look tomorrow Friday before noon, and ping someone for a review when I feel it's ready.

This PR should close https://github.com/pyxem/orix-demos/issues/24, https://github.com/pyxem/orix-demos/issues/23, https://github.com/pyxem/orix-demos/issues/21, https://github.com/pyxem/orix-demos/issues/19, and replace #135.

I suggest we replace the [orix-demos repository](https://github.com/pyxem/orix-demos) with notebooks included as user guides in the `doc/` directory. We can discuss this in a later PR where I plan to move the CrystalMap notebook over to this repository.

### CODE REVIEW

**Comment by hakonanes** [comment]
Note that with this setup, the notebooks are run with nbsphinx for every RtD PR check, so any intended workflow etc. can be checked continuously (as long as we make PRs).

**Comment by hakonanes** [comment]
My issue with getting RtD to build the docs (which I don't experience with kikuchipy) is most likely related to https://github.com/spatialaudio/nbsphinx/issues/121, will try the solutions suggested there.

**Comment by hakonanes** [comment]
The updated Sphinx documentation can now be seen here: https://orix--152.org.readthedocs.build/en/152/stereographic_projection.html

**Comment by pc494** [comment]
@hakonanes, this is excellent.

The only change I'm not sure about is dropping the CHANGELOG into the doc/ folder, I think having it at the top level is a good idea. As a compromise, would it be reasonable to have a released versions only CHANGELOG in doc/ and the CHANGELOG.md as it was? My thinking is that if you are looking for code changes on the website, you probably are building a release version? Does that seem convincing to you?

**Comment by hakonanes** [comment]
I moved `CHANGELOG.rst` back to the top level directory, and replaced it with `doc/changelog.rst`, a stub file linking to the original file, so that it can be included in the table of contents tree (toctree). What do you think, @pc494?

Note that the changelog file still should be a reST file, unless we would like to add another doc dependency (sphinx extension m2r2) to convert Markdown to reST.

**Comment by pc494** [comment]
This seems fine to me, but it's good to know we can workaround it later if needs be. I'm now merging the PR

**Comment by hakonanes** [comment]
The stereographic projection notebook interactivelly in the browser with Binder: https://mybinder.org/v2/gh/pyxem/orix/master?filepath=doc/stereographic_projection.ipynb

**Pull request merged**
